apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: compiler
  labels: 
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: country
                operator: In
                values:
                - India
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        env:
        - name: Password
          valueFrom:
            secretKeyRef:
              name: secret
              key:  password
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: configfile
              key:  port


